//***************************************************************************
//                          pvapp.h  -  description
//                             -------------------
//  begin            : So Nov 2 12:04:51 2008
//  generated by     : pvdevelop (C) 2000-2007 by Lehrig Software Engineering
//  email            : lehrig@t-online.de
//***************************************************************************
#ifndef _PVAPP_H_
#define _PVAPP_H_

//##################################
// include rllib and pvb
//################################## 
#include "processviewserver.h"
#include "rldataacquisition.h"

//###################################
static int trace=1; // todo: set trace=0 if you do not want printf() within event loop

int show_mask1(PARAM *p);

#endif
