shell/make.sh ./demos/statedesigner $1
shell/make.sh ./demos/siemenstcp $1
shell/make.sh ./demos/raspberry_pi/pigpio $1
shell/make.sh ./demos/hellocpp $1
shell/make.sh ./demos/modbusserial $1
shell/make.sh ./demos/svgdemo $1
shell/make.sh ./demos/svgdemo/fake_model $1
shell/make.sh ./demos/svgdemo/pvserver $1
shell/make.sh ./demos/svgdemo/docs/pvsexample $1
shell/make.sh ./demos/webcam $1
shell/make.sh ./demos/hilschercif $1
shell/make.sh ./demos/hellopython $1
shell/make.sh ./demos/modbus_aqui $1
shell/make.sh ./demos/eibnetip $1
shell/make.sh ./demos/pvgrep $1
shell/make.sh ./demos/restroom $1
shell/make.sh ./demos/modbus_example $1
shell/make.sh ./pcontrol $1
shell/make.sh ./custom_widgets/embedded_widgets/embedded_widgets_1 $1
shell/make.sh ./custom_widgets/embedded_widgets/pvsEmbeddedWidgetsSample $1
shell/make.sh ./project_template/pvserver/pvs1 $1
shell/make.sh ./templates/qtDatabase $1
shell/make.sh ./templates/additional_threads_for_continuous_tasks $1
shell/make.sh ./templates/statemachine/plc $1
shell/make.sh ./templates/statemachine/pvs $1
shell/make.sh ./templates/myeventhandler $1
shell/make.sh ./templates/alarm $1
shell/make.sh ./templates/pvb_com_plugin/server $1
shell/make.sh ./templates/pvb_com_plugin/client $1
shell/make.sh ./templates/qtpvbinding $1
shell/make.sh ./templates/weblayout $1
shell/make.sh ./daemons/siemenstcp/client $1
shell/make.sh ./daemons/siemenstcp/pvs $1
shell/make.sh ./daemons/ethernetip/client $1
shell/make.sh ./daemons/ethernetip/pvs $1
shell/make.sh ./daemons/eibnet/client $1
shell/make.sh ./daemons/eibnet/pvs $1
shell/make.sh ./daemons/modbus/modbus_tcp_simulation_and_server $1
shell/make.sh ./daemons/modbus/client $1
shell/make.sh ./daemons/modbus/pvs $1
shell/make.sh ./daemons/libnodave $1
shell/make.sh ./daemons/webcam/client $1
shell/make.sh ./daemons/webcam/pvs $1
shell/make.sh ./daemons/siemensppi/client $1
shell/make.sh ./daemons/siemensppi/pvs $1
shell/make.sh ./daemons/opcxmlda/client $1
shell/make.sh ./daemons/opcxmlda/pvs $1
shell/make.sh ./daemons/textobserver/client $1
shell/make.sh ./daemons/textobserver/pvs $1
