//***************************************************************************
//                          pvapp.h  -  description
//                             -------------------
//  begin            : Mo. Nov. 27 08:56:13 2017
//  generated by     : pvdevelop (C) Lehrig Software Engineering
//  email            : lehrig@t-online.de
//***************************************************************************
#ifndef _PVAPP_H_
#define _PVAPP_H_

#ifdef USE_INETD
static int trace=0; // todo: set trace=0 if you do not want printf() within event loop
#else
static int trace=0; // todo: set trace=0 if you do not want printf() within event loop
#endif

#include "processviewserver.h"
#include "rlspreadsheet.h"
#include "pvcairo.h"
#include "pvcairowidget.h"
#include "pvcairovdi.h"

#define PNG_FILENAME1 "test.png"
#define SVG_FILENAME1 "test.svg"
// todo: comment me out
//#include "rlmodbusclient.h"
//#include "rlsiemenstcpclient.h"
//#include "rlppiclient.h"
//#include "modbusdaemon.h"             // this is generated. Change for name.h -> "name.mkmodbus"
//#include "siemensdaemon.h"            // this is generated
//#include "ppidaemon.h"                // this is generated

int show_mask1(PARAM *p);

int runHttpServer(PARAM *p);

#endif
