kate \
./demos/statedesigner/pvs.pro \
./demos/siemenstcp/pvs.pro \
./demos/raspberry_pi/pigpio/pvs.pro \
./demos/hellocpp/pvs.pro \
./demos/modbusserial/pvs.pro \
./demos/svgdemo/pvs.pro \
./demos/svgdemo/fake_model/fake_model.pro \
./demos/svgdemo/pvserver/RealTimePVB.pro \
./demos/svgdemo/docs/pvsexample/pvsexample.pro \
./demos/hilschercif/pvs.pro \
./demos/hellopython/pvs.pro \
./demos/modbus_aqui/pvs.pro \
./demos/eibnetip/pvs.pro \
./demos/pvgrep/pvgrep.pro \
./demos/restroom/pvs.pro \
./demos/modbus_example/pvs.pro \
./pcontrol/pvs.pro \
./custom_widgets/embedded_widgets/embedded_widgets_1/embedded_widgets.pro \
./custom_widgets/embedded_widgets/pvsEmbeddedWidgetsSample/pvsEmbeddedWidgetsSample.pro \
..pro \ject_template/pvserver/pvs1/pvs.pro \
./templates/qtDatabase/pvs.pro \
./templates/additional_threads_for_continuous_tasks/pvs.pro \
./templates/statemachine/plc/plc.pro \
./templates/statemachine/pvs/pvs.pro \
./templates/myeventhandler/pvs.pro \
./templates/alarm/pvs.pro \
./templates/pvb_com_plugin/server/pvs_com_plugin.pro \
./templates/pvb_com_plugin/client/pvb_com_plugin.pro \
./templates/qtpvbinding/pvs.pro \
./templates/weblayout/pvs.pro \
./daemons/siemenstcp/client/siemenstcp_client.pro \
./daemons/siemenstcp/pvs/pvs.pro \
./daemons/ethernetip/client/ethernetip_client.pro \
./daemons/ethernetip/pvs/pvs.pro \
./daemons/eibnet/client/eibnet_client.pro \
./daemons/eibnet/pvs/pvs.pro \
./daemons/modbus/modbus_tcp_simulation_and_server/mtss.pro \
./daemons/modbus/client/modbus_client.pro \
./daemons/modbus/pvs/pvs.pro \
./daemons/libnodave/ppidaemon.pro \
./daemons/siemensppi/client/siemensppi_client.pro \
./daemons/siemensppi/pvs/pvs.pro \
./daemons/opcxmlda/client/opcxmlda_client.pro \
./daemons/opcxmlda/pvs/pvs.pro
