//***************************************************************************
//                          pvapp.h  -  description
//                             -------------------
//  begin            : Mo. Okt. 24 14:29:28 2016
//  generated by     : pvdevelop (C) Lehrig Software Engineering
//  email            : lehrig@t-online.de
//***************************************************************************
#ifndef _PVAPP_H_
#define _PVAPP_H_

static int trace=1; // todo: set trace=0 if you do not want printf() within event loop

#include "rlsocket.h"
#include "rlthread.h"
#include "openssl/ssl.h"
#include "openssl/bio.h"
#include "openssl/err.h"
#include "stdio.h"
#include "string.h"

#endif
