//***************************************************************************
//                          pvapp.h  -  description
//                             -------------------
//  begin            : Do Apr 12 12:10:56 2007
//  generated by     : pvdevelop (C) 2000-2007 by Lehrig Software Engineering
//  email            : lehrig@t-online.de
//***************************************************************************
#ifndef _PVAPP_H_
#define _PVAPP_H_

// todo: adjust this
#define DEBUG
//#define EIB_LOCALHOST  "nb4lehrig"
#define EIB_LOCALHOST  "192.168.1.35"
#define EIB_GATEWAY    "192.168.1.102"
#define EIB_MAXSIGNALS 1000

#include "processviewserver.h"
// todo: comment me out
//#include "rlmodbusclient.h"
//#include "rlsiemenstcpclient.h"
//#include "rlppiclient.h"
//#include "modbusdaemon.h"             // this is generated
//#include "siemensdaemon.h"            // this is generated
//#include "ppidaemon.h"                // this is generated
#include "rleibnetip.h"
#include <ctype.h>

int show_mask1(PARAM *p);

#endif
