//***************************************************************************
//                          pvapp.h  -  description
//                             -------------------
//  begin            : Mi Sep 16 09:47:34 2009
//  generated by     : pvdevelop (C) Lehrig Software Engineering
//  email            : lehrig@t-online.de
//***************************************************************************
#ifndef _PVAPP_H_
#define _PVAPP_H_

static int trace=1; // todo: set trace=0 if you do not want printf() within event loop

#include "processviewserver.h"
#include "rlsvganimator.h"
// todo: comment me out
//#include "rlmodbusclient.h"
//#include "rlsiemenstcpclient.h"
//#include "rlppiclient.h"
//#include "modbusdaemon.h"             // this is generated
//#include "siemensdaemon.h"            // this is generated
//#include "ppidaemon.h"                // this is generated

int show_mask1(PARAM *p);

#endif
