#ifndef EMBEDDED_WIDGETS_GLOBAL_H
#define EMBEDDED_WIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EMBEDDED_WIDGETS_LIBRARY)
#  define EMBEDDED_WIDGETSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EMBEDDED_WIDGETSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EMBEDDED_WIDGETS_GLOBAL_H
