call bat\make_module.bat demos\statedesigner pvs.pro
call bat\make_module.bat demos\siemenstcp pvs.pro
call bat\make_module.bat demos\raspberry_pi\pigpio pvs.pro
call bat\make_module.bat demos\hellocpp pvs.pro
call bat\make_module.bat demos\modbusserial pvs.pro
call bat\make_module.bat demos\svgdemo pvs.pro
call bat\make_module.bat demos\svgdemo\fake_model fake_model.pro
call bat\make_module.bat demos\svgdemo\pvserver RealTimePVB.pro
call bat\make_module.bat demos\svgdemo\docs\pvsexample pvsexample.pro
call bat\make_module.bat demos\webcam pvs.pro
call bat\make_module.bat demos\hilschercif pvs.pro
call bat\make_module.bat demos\hellopython pvs.pro
call bat\make_module.bat demos\modbus_aqui pvs.pro
call bat\make_module.bat demos\eibnetip pvs.pro
call bat\make_module.bat demos\pvgrep pvgrep.pro
call bat\make_module.bat demos\restroom pvs.pro
call bat\make_module.bat demos\modbus_example pvs.pro
call bat\make_module.bat pcontrol pvs.pro
call bat\make_module.bat custom_widgets\embedded_widgets\embedded_widgets_1 embedded_widgets.pro
call bat\make_module.bat custom_widgets\embedded_widgets\pvsEmbeddedWidgetsSample pvsEmbeddedWidgetsSample.pro
call bat\make_module.bat project_template\pvserver\pvs1 pvs.pro
call bat\make_module.bat templates\qtDatabase pvs.pro
call bat\make_module.bat templates\additional_threads_for_continuous_tasks pvs.pro
call bat\make_module.bat templates\statemachine\plc plc.pro
call bat\make_module.bat templates\statemachine\pvs pvs.pro
call bat\make_module.bat templates\myeventhandler pvs.pro
call bat\make_module.bat templates\alarm pvs.pro
call bat\make_module.bat templates\pvb_com_plugin\server pvs_com_plugin.pro
call bat\make_module.bat templates\pvb_com_plugin\client pvb_com_plugin.pro
call bat\make_module.bat templates\qtpvbinding pvs.pro
call bat\make_module.bat templates\weblayout pvs.pro
call bat\make_module.bat daemons\siemenstcp\client siemenstcp_client.pro
call bat\make_module.bat daemons\siemenstcp\pvs pvs.pro
call bat\make_module.bat daemons\ethernetip\client ethernetip_client.pro
call bat\make_module.bat daemons\ethernetip\pvs pvs.pro
call bat\make_module.bat daemons\eibnet\client eibnet_client.pro
call bat\make_module.bat daemons\eibnet\pvs pvs.pro
call bat\make_module.bat daemons\modbus\modbus_tcp_simulation_and_server mtss.pro
call bat\make_module.bat daemons\modbus\client modbus_client.pro
call bat\make_module.bat daemons\modbus\pvs pvs.pro
call bat\make_module.bat daemons\libnodave ppidaemon.pro
call bat\make_module.bat daemons\webcam\client webcam_client.pro
call bat\make_module.bat daemons\webcam\pvs pvs.pro
call bat\make_module.bat daemons\siemensppi\client siemensppi_client.pro
call bat\make_module.bat daemons\siemensppi\pvs pvs.pro
call bat\make_module.bat daemons\opcxmlda\client opcxmlda_client.pro
call bat\make_module.bat daemons\opcxmlda\pvs pvs.pro
call bat\make_module.bat daemons\textobserver\client textobserver_client.pro
call bat\make_module.bat daemons\textobserver\pvs pvs.pro
